---
apiVersion: rbac.authorization.k8s.io/v1  
kind: ClusterRoleBinding
metadata:
  name: acm-policy-generator-mutator
roleRef:
  kind: ClusterRole
  apiGroup: rbac.authorization.k8s.io
  name: system:auth-delegator
subjects:
- kind: ServiceAccount
  namespace: acm-policy-generator
  name: mutator

---
apiVersion: rbac.authorization.k8s.io/v1  
kind: ClusterRole
metadata:
  name: acm-policy-generator:mutator
rules:
- apiGroups:
  - bry.redhat.io
  resources:
  - mutationservice  
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - admission.bry.redhat.io
  resources:
  - mutationservice 
  verbs:
  - create

---
apiVersion: rbac.authorization.k8s.io/v1  
kind: ClusterRoleBinding
metadata:
  name: acm-policy-generator-mutator-webhook
roleRef:
  kind: ClusterRole
  apiGroup: rbac.authorization.k8s.io
  name: acm-policy-generator:mutator
subjects:
- kind: ServiceAccount
  namespace: acm-policy-generator
  name: mutator

---
apiVersion: rbac.authorization.k8s.io/v1  
kind: RoleBinding
metadata:
  namespace: kube-system
  name: extension-apimutator-authentication-reader-acm-policy-generator-mutator
roleRef:
  kind: Role
  apiGroup: rbac.authorization.k8s.io
  name: extension-apimutator-authentication-reader
subjects:
- kind: ServiceAccount
  namespace: acm-policy-generator
  name: mutator

---
apiVersion: rbac.authorization.k8s.io/v1  
kind: ClusterRole
metadata:
  name: acm-policy-generator-mutator-role
rules:
- apiGroups:
  - admissionregistration.k8s.io
  resources:
  - validatingwebhookconfigurations
  - mutatingwebhookconfigurations
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - list
  - watch

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: acm-policy-generator-mutator-role
roleRef:
  kind: ClusterRole
  apiGroup: rbac.authorization.k8s.io
  name: acm-policy-generator-mutator-role
subjects:
- kind: ServiceAccount
  namespace: acm-policy-generator
  name: mutator