apiVersion: v1
kind: Service
metadata:
  name: gitopts-repo-mutator
  namespace: acm-policy-generator
  labels:
    app: gitopts-repo-mutator
  annotations:
    service.beta.openshift.io/serving-cert-secret-name: webhook-certs
spec:
  ports:
  - port: 443
    targetPort: 9443
  selector:
    app: gitopts-repo-mutator
